# Start with a base image containing Java runtime
FROM java:8

RUN mkdir -p /home/files/companyfile/

VOLUME ["/home/ec2-user/fileROOT/","/home/ec2-user/fileROOT/"]

# Make port 8080 available to the world outside this container
EXPOSE 80

# The application's jar file
ARG JAR_FILE=target/goodfinger-project-0.0.1-SNAPSHOT.jar

# Add the application's jar to the container
ADD ${JAR_FILE} goodfinger2-springboot.jar

# Run the jar file
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/goodfinger2-springboot.jar"]

