# Start with a base image containing Java runtime
FROM openjdk:8-alpine

# Add Author info
LABEL maintainer="h1o1n1g1@nate.com"

# Add a volume to /tmp
VOLUME /tmp

# Make port 8080 available to the world outside this container
EXPOSE 80

# The application's jar file
ARG JAR_FILE=build/libs/*.jar

# Add the application's jar to the container
ADD ${JAR_FILE} goodfinger-dphong.jar

# Run the jar file
ENTRYPOINT ["java","-jar","/goodfinger-dphong.jar"]
